name: bn-medical
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8.19
  - pip
  - numpy
  - pip:
    - pgmpy
    - rapidfuzz
    - igraph
    - xgboost
    - imbalanced-learn
    - pandas